apiVersion: apps/v1
kind: Deployment
metadata:
  name: duck-pic-app
spec:
  selector:
    matchLabels:
      app: duck-pic-app
  template:
    metadata:
      labels:
        app: duck-pic-app
    spec:
      containers:
        - name: duck-pic-app
          image: rakhmadbudiono/duck-pic-service:latest
          resources:
            limits:
              memory: "128Mi"
              cpu: "250m"
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: duck-pic-service
spec:
  type: LoadBalancer
  selector:
    app: duck-pic-app
  ports:
    - port: 80
      targetPort: 8000
